name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Check system info
        shell: pwsh
        run: |
          Write-Host "System Information:"
          systeminfo | Select-String "OS Name", "OS Version"
          Write-Host "`nJava Version:"
          java -version
          
      - name: Checking Java Version
        run: |
          echo ----- Java Version -----
          java --version
          
      - name: Create test file
        shell: pwsh
        run: |
          Write-Host "Creating test file..."
          "Test file" | Out-File -FilePath test.txt
          Write-Host "`nFile:"
          Get-Content test.txt
