name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Check system info
        shell: pwsh
        run: |
          Write-Host "System Information:"
          systeminfo | Select-String "OS Name", "OS Version"
          Write-Host "`nJava Version:"
          java -version
          
      - name: Install additional software
        shell: pwsh
        run: |
          Write-Host "Installing curl using Chocolatey..."
          choco install -y curl
          Write-Host "`nCurl Version:"
          curl --version
          
      - name: Create test file
        shell: pwsh
        run: |
          Write-Host "Creating test file..."
          "This is a test file created by the self-hosted runner" | Out-File -FilePath test.txt
          Write-Host "`nFile contents:"
          Get-Content test.txt
