name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Check system info
        shell: powershell
        run: | 
          systeminfo | Select-String "OS Name", "OS Version" 
          java -version 

      - name: Additional software
        shell: powershell
        run: | 
          choco install -y curl 
          curl --version
