name: Self-hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Check system info
        shell: powershell
        run: | 
          systeminfo | Select-String "OS Name", "OS Version" 
          java -version 

      - name: Install 7zip
        shell: powershell
        run: |
          Write-Host "Installing 7zip using Chocolatey..."
          choco install -y 7zip
          Write-Host "`n7zip Version:"
          7z i
