name: Exemplo de Permissões e GITHUB_TOKEN
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  simular_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simular um deploy
        id: deploy
        run: |
          echo "Tentando realizar o deploy..."
          exit 1

      - name: Criar issue sobre a falha
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Falha: ${context.workflow}`,
              body: `Ocorreu um erro na execução do workflow.

              - Workflow: ${context.workflow}
              - Job: ${context.job}
              - Link para a execução: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })
