name: Exemplo de Variáveis e Secrets

on:
  workflow_dispatch:
jobs:
  variables-and-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Mostrar variáveis de configuração
        run: |
          echo "Modo: ${{ vars.APP_MODE }}"
          echo "E-mail: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular um passo de autenticação
        run: |
          echo "Iniciando autenticação..."
          # --token=${{ secrets.PROD_TOKEN }}
          echo "Autenticação com o token concluída."
